apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: button
  namespace: prod
spec:
  selector:
    matchLabels:
      app: button
  replicas: 6
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 6
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Changed this to green"
      labels:
        app: button
    spec:
      containers:
      - name: button
        image: gcr.io/deployments-demo/button:green
        ports:
          - containerPort: 3000
            name: http
            protocol: TCP
